version: "3.1"
services: 
  db:
    container_name: db
    build: ./model/
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      # - ./database/setup.sql:/docker-entrypoint-initdb.d
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
    - 3306:3306
  grofers-api:
    build: .
    container_name: grofers-api
    ports: 
      - 3000:3000
    volumes:
      - .:/go/src/github.com/angadsharma1016/grofers-task
    depends_on:
      - db
    env_file: ./.env
    restart: on-failure
  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222 # for clients
      - 8222:8222 # HTTP management port for reporting
      - 6222:6222 # routing port for clustering

